# Generated by Django 5.2.1 on 2025-06-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("due_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("teacher_remark", models.TextField(blank=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="assignments/pdfs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("course", models.CharField(max_length=100)),
                (
                    "roll_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id_no", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("subject", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "submitted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="assignments/pdfs/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Submitted", "Submitted"),
                            ("Reviewed", "Reviewed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateField()),
                ("student_remark", models.TextField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="HomeWork.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="HomeWork.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HomeWork.teacher"
            ),
        ),
        migrations.CreateModel(
            name="TeacherReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_grade", models.CharField(max_length=10)),
                ("teacher_review", models.CharField(max_length=100)),
                ("reviewed_at", models.DateTimeField()),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="HomeWork.studentsubmission",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HomeWork.teacher",
                    ),
                ),
            ],
        ),
    ]
