# Generated by Django 5.2.1 on 2026-01-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomeWork", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id_no",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
